---

- hosts: routers
  gather_facts: false
  connection: local

  tasks:
    - name: add DHCP pools
      ios_config:
        lines:
          - network 10.10.40.0 255.255.255.0
          - default-router 10.10.40.254
        parents: ip dhcp pool VLAN0040

    - name: Add interface
      ios_config:
        lines:
          - ip address 10.10.40.254 255.255.255.0
          - ip nat inside
        parents: interface vlan 40

    - name: Add allowed vlan to trunk
      ios_config:
        lines:
          - switchport trunk allowed vlan add 40
        parents: interface gigabitEthernet 0/1/0


- hosts: switches
  gather_facts: false
  connection: local

  tasks:
    - name: Add vlan
      ios_config:
        lines:
          -  name MISC
        parents: vlan 40

    - name: change switchports
      ios_config:
        lines:
          - switchport mode access
          - switchport access vlan 40
        parents: interface gigabitEthernet1/0/12

    - name: Add allowed vlan to trunk
      ios_config:
        lines:
          - switchport trunk allowed vlan add 40
        parents: interface gigabitEthernet 1/0/13
