---

- hosts: all-network
  gather_facts: false
  connection: local

  tasks:
    - name: Change SNMP strings for all devices
      ios_config:
        lines:
          - snmp-server community snmp-changed RW
          - no snmp-server community cisco RW
