---
## Playbook to get system time and append it to backup files

- hosts: localhost

  tasks:
   - name: Get ansible date/time facts
     setup:
       filter: "ansible_date_time"
       gather_subset: "!all"

   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"

   - name: Create Directory
     file:
      path: ../network-configs/
      state: directory
  run_once: true

- hosts: all-network
  gather_facts: false
  connection: local

  tasks:
   - name: Backup all devices
     ios_command:
       commands: show run
     register: config

   - name: Save output to ../network-configs
     copy:
       content: "{{config.stdout[0]}}"
       dest: "../network-configs/{{inventory_hostname}}"
